# Generated by Django 4.1.13 on 2026-02-02 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Admin', 'Admin')], default='Employee', max_length=20, verbose_name='User Role'),
        ),
        migrations.CreateModel(
            name='Employee_Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_start_date', models.DateField(verbose_name='Leave Start Date')),
                ('leave_end_date', models.DateField(verbose_name='Leave End Date')),
                ('reason', models.TextField(verbose_name='Reason for Leave')),
                ('Leave_type', models.CharField(choices=[('half-day', 'Half Day'), ('full-day', 'Full Day')], max_length=50, verbose_name='Type of Leave')),
                ('Leave_Status', models.CharField(default='Pending', max_length=20, verbose_name='Leave Status')),
                ('Leave_count', models.IntegerField(verbose_name='Number of Leave Days')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.employee')),
            ],
        ),
    ]
